version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dotnet:
        patterns:
          - "Microsoft.*"
        exclude-patterns:
          - "Microsoft.Extensions.Configuration.AzureAppConfiguration"
      serilog:
        patterns:
          - "Serilog"
          - "Serilog.*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
