name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v1
        id: dependabot-metadata

      - run: echo "$STEPS_CONTEXT"
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
